# Generated by Django 3.2.8 on 2021-12-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_App', '0002_alter_tasks_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='task_status',
        ),
    ]
