# Generated by Django 3.2.8 on 2021-12-18 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('to_do_App', '0003_remove_tasks_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_to_perform', to=settings.AUTH_USER_MODEL),
        ),
    ]
